### ISSUE TITLE
How to obtain model blobs?

### ISSUE THREAD

**Issue by vipulkumar-developer** [kschlegel/OAK-HumanPoseEstimation#2]
I've an issue in the following line of code
`model_blob = (model_config["blob"] + "_sh" + str(model_config["shaves"]) +
                  ".blob")`
Because there is no blob file present in the repository. Where can I obtain these blob files?

**Comment by kschlegel** [comment]
Have a look through the readme of the project. In the setup section you'll find that the model blobs can be downloaded from here: https://drive.google.com/file/d/1AUszSCMSc5dCATnZn1jK8PzMMyLQ__5M/view?usp=sharing

**Comment by vipulkumar-developer** [comment]
Ok thank you very much, it was a silly question since now I've noted the drive link in the README.
